name: Annotation
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::notice::This is a notice."
      - run: echo "::warn::This is a warn."
      - run: echo "::error::This is a error."
