name: Choice
on:
  dispatch_workflow:
    inputs:
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: "echo ${{ inputs.log-level }}"
