name: Choice
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        options:
          - info
          - warn
          - error
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      LOG_LEVEL: ${{ inputs.log-level }}
    steps:
      - run: echo "${LOG_LEVEL}"
