name: GitHub output
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - run: echo "${RESULT}"
        env:
          RESULT: ${{ steps.source.outputs.result }}
